include current-theme.conf
font_family JetBrains Mono Nerd Font
disable_ligatures never

kitty_mod ctrl+shift
map kitty_mod+l scroll_lineleft
map kitty_mod+j scroll_linedown
map kitty_mod+k scroll_lineup
map kitty_mod+l scroll_lineright

background_opacity 0.9

confirm_os_windows_close 0
